### PR TITLE
Stakers leaderboard

### PR DESCRIPTION
**Pull request by yasmine9**

### CODE REVIEW

**Review by EdgarBarrantes — COMMENTED** [review]
This seems pretty good, the only two improvements that I'd make would be:
- Make the colours in the buttons match the existing colours for each asset (if not selected it could have higher transparency)
- The amounts in total staked could follow a two digit format, e.g.: 234.32, 200.00.
Wdyt?

**Comment by swapnilraj** [comment]
Left some comments on the preview, additionally on mobile the table doesn't scroll horizontally.

**Comment by yasmine9** [comment]
All comments were addressed, ready for a re-review 

An improvement is to implement caching in server side for ens names, I can work on this next

**Comment by EdgarBarrantes** [comment]
Closing as discussed though chat and due to #28

**Pull request closed without merging**
